// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using School_Core.API.Contexts;

namespace School_Core.API.Migrations
{
    [DbContext(typeof(SchoolMedicalDbContext))]
    partial class SchoolMedicalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("School_Core.API.Models.SickLeave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SickLeaves");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb7bde3e-1c7e-4a71-bd02-3903be8f9ea2"),
                            DateFrom = new DateTime(2020, 11, 3, 12, 53, 18, 202, DateTimeKind.Local).AddTicks(3797),
                            Reason = "DummyReason1",
                            StudentId = new Guid("90a4faf7-33d9-4bf5-8584-1f92e80db0cb")
                        },
                        new
                        {
                            Id = new Guid("4ccdc39b-c060-428e-9d4c-cb6b4834ed10"),
                            DateFrom = new DateTime(2020, 11, 3, 12, 53, 18, 204, DateTimeKind.Local).AddTicks(9926),
                            Reason = "DummyReason2",
                            StudentId = new Guid("b92bef62-3853-4b21-a6f4-c6f11bf91a9b")
                        },
                        new
                        {
                            Id = new Guid("cceba541-85c9-4f3f-97c4-c9629e1e0200"),
                            DateFrom = new DateTime(2020, 11, 3, 12, 53, 18, 204, DateTimeKind.Local).AddTicks(9968),
                            Reason = "DummyReason3",
                            StudentId = new Guid("3f413ea5-a53f-472b-85da-a0d2c0afca6c")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
